# -*- coding: utf-8 -*-
"""Aryaman_Gudwani_102317279_Lab8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12IDCtT0FQmvC39TaKcviMt6WH00syRI9
"""

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score

data = load_iris()
features = data.data
target = data.target

X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

log_reg_model = LogisticRegression(max_iter=1000)

log_reg_model.fit(X_train, y_train)

predictions = log_reg_model.predict(X_test)

model_accuracy = accuracy_score(y_test, predictions)
print("Model Accuracy:", model_accuracy)